"""create_orders_table

Revision ID: 0584a224ff76
Revises: 139553ef5dae
Create Date: 2025-11-11 12:15:25.140508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0584a224ff76'
down_revision = '139553ef5dae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Fix assets table structure
    op.alter_column('assets', 'asset_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('equity', 'etf', 'forex', 'crypto', 'future', 'option', 'bond', 'other', name='assettype', native_enum=False),
               existing_nullable=False)
    op.alter_column('assets', 'meta_json',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('uq_asset_exchange_symbol', 'assets', type_='unique')
    op.create_index('ix_assets_active', 'assets', ['is_active'], unique=False)
    op.create_index('ix_assets_exchange', 'assets', ['exchange'], unique=False)
    op.create_index('ix_assets_symbol', 'assets', ['symbol'], unique=False)
    op.create_index('ix_assets_type', 'assets', ['asset_type'], unique=False)
    op.create_unique_constraint('uq_assets_exchange_symbol', 'assets', ['exchange', 'symbol'])
    
    # Drop old orders table and recreate with new schema
    op.drop_table('orders')
    
    # Drop old enum types if they exist
    op.execute("DROP TYPE IF EXISTS orderside CASCADE")
    op.execute("DROP TYPE IF EXISTS orderstatus CASCADE")
    
    # Create new enum types
    op.execute("CREATE TYPE orderside AS ENUM ('buy', 'sell')")
    op.execute("CREATE TYPE orderstatus AS ENUM ('new', 'pending_broker', 'partially_filled', 'filled', 'canceled', 'rejected', 'expired')")
    op.execute("CREATE TYPE ordertype AS ENUM ('market', 'limit', 'stop', 'stop_limit')")
    op.execute("CREATE TYPE timeinforce AS ENUM ('day', 'gtc', 'fok', 'ioc')")
    op.execute("CREATE TYPE quantitytype AS ENUM ('units', 'notional')")
    op.execute("CREATE TYPE positioneffect AS ENUM ('open', 'close', 'auto')")
    op.execute("CREATE TYPE broker AS ENUM ('paper', 'alpaca', 'binance', 'ibkr')")
    
    # Create new orders table with correct schema
    op.create_table('orders',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('symbol_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('strategy_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('account_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('side', sa.Enum('buy', 'sell', name='orderside', native_enum=False), nullable=False),
        sa.Column('type', sa.Enum('market', 'limit', 'stop', 'stop_limit', name='ordertype', native_enum=False), nullable=False),
        sa.Column('time_in_force', sa.Enum('day', 'gtc', 'fok', 'ioc', name='timeinforce', native_enum=False), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
        sa.Column('quantity_type', sa.Enum('units', 'notional', name='quantitytype', native_enum=False), nullable=False),
        sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column('stop_price', sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column('reduce_only', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('position_effect', sa.Enum('open', 'close', 'auto', name='positioneffect', native_enum=False), nullable=False),
        sa.Column('status', sa.Enum('new', 'pending_broker', 'partially_filled', 'filled', 'canceled', 'rejected', 'expired', name='orderstatus', native_enum=False), nullable=False, server_default=sa.text("'new'")),
        sa.Column('average_fill_price', sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column('filled_quantity', sa.Numeric(precision=28, scale=10), nullable=False, server_default=sa.text('0')),
        sa.Column('broker', sa.Enum('paper', 'alpaca', 'binance', 'ibkr', name='broker', native_enum=False), nullable=False),
        sa.Column('broker_order_id', sa.String(length=128), nullable=True),
        sa.Column('client_order_id', sa.String(length=128), nullable=True),
        sa.Column('paper', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    )
    
    # Create indexes
    op.create_index('ix_orders_broker_broker_order_id', 'orders', ['broker', 'broker_order_id'], unique=False)
    op.create_index('ix_orders_created_symbol_status', 'orders', ['created_at', 'symbol_id', 'status'], unique=False)
    op.create_unique_constraint('uq_orders_account_client_order_id', 'orders', ['account_id', 'client_order_id'])
    
    # Fix symbols table - drop old index and rely on unique constraint from earlier migration
    op.drop_index('ix_symbols_symbol', table_name='symbols')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate old symbols index
    op.create_index('ix_symbols_symbol', 'symbols', ['symbol'], unique=True)
    
    # Drop new orders table
    op.drop_table('orders')
    
    # Recreate old orders table structure
    op.create_table('orders',
        sa.Column('id', sa.INTEGER(), autoincrement=True, primary_key=True),
        sa.Column('broker_order_id', sa.VARCHAR(length=64), nullable=True),
        sa.Column('symbol', sa.VARCHAR(length=20), nullable=False),
        sa.Column('side', postgresql.ENUM('buy', 'sell', name='orderside'), nullable=False),
        sa.Column('qty', sa.INTEGER(), nullable=False),
        sa.Column('limit_price', sa.NUMERIC(precision=18, scale=6), nullable=True),
        sa.Column('status', postgresql.ENUM('new', 'submitted', 'filled', 'canceled', 'rejected', name='orderstatus'), nullable=False, server_default=sa.text("'new'::orderstatus")),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    )
    op.create_index('ix_orders_symbol', 'orders', ['symbol'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_broker_order_id', 'orders', ['broker_order_id'], unique=False)
    
    # Revert assets table changes
    op.drop_constraint('uq_assets_exchange_symbol', 'assets', type_='unique')
    op.drop_index('ix_assets_type', table_name='assets')
    op.drop_index('ix_assets_symbol', table_name='assets')
    op.drop_index('ix_assets_exchange', table_name='assets')
    op.drop_index('ix_assets_active', table_name='assets')
    op.create_unique_constraint('uq_asset_exchange_symbol', 'assets', ['exchange', 'symbol'])
    op.alter_column('assets', 'meta_json',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('assets', 'asset_type',
               existing_type=sa.Enum('equity', 'etf', 'forex', 'crypto', 'future', 'option', 'bond', 'other', name='assettype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###