"""create strategies table

Revision ID: b95cc4f68f6c
Revises: 2025_11_10_0001
Create Date: 2025-11-10 21:04:34.702800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b95cc4f68f6c'
down_revision = '2025_11_10_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create strategies table
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_strategy_name')
    )
    
    # Create ENUM types only if they don't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE orderside AS ENUM ('buy', 'sell');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE orderstatus AS ENUM ('new', 'submitted', 'filled', 'canceled', 'rejected');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Alter side column: drop default, change type, restore default
    op.execute("ALTER TABLE orders ALTER COLUMN side DROP DEFAULT")
    op.execute("ALTER TABLE orders ALTER COLUMN side TYPE orderside USING side::orderside")
    
    # Alter status column: drop default, change type, restore default
    op.execute("ALTER TABLE orders ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE orders ALTER COLUMN status TYPE orderstatus USING status::orderstatus")
    op.execute("ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'new'::orderstatus")
    
    # Make timestamp columns NOT NULL
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    
    # Convert back to VARCHAR
    op.execute("ALTER TABLE orders ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE orders ALTER COLUMN status TYPE VARCHAR")
    op.execute("ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'new'")
    
    op.execute("ALTER TABLE orders ALTER COLUMN side TYPE VARCHAR")
    
    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS orderstatus")
    op.execute("DROP TYPE IF EXISTS orderside")
    
    op.drop_table('strategies')
    # ### end Alembic commands ###